manifest = "d55db3dbf9bb8e0c3e00a3907383d18bac0dbc71cf9dfd293fca9a0cd0e0132b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.30.1" ]
revision = "211cb1839d5488e44299309a5af011b0a9dff8d3"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.30.1" ]
revision = "5ffdf499e338c885abf953360a334b3d3ba71c96"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.30.1" ]
revision = "b2d6df042e39f9aad64ed6c78942dc95f4483762"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.30.1" ]
revision = "b1754492ee082040d3d9868df4d8151fcfd5c438"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.30.1" ]
revision = "504cc3cb91028452b397806c6c9bce4c2cee3a78"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.30.1" ]
revision = "a88739e04cc0f241c094e641574672f00c61bc40"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.30.1" ]
revision = "a31a71bb5ec767d069628c8d6f26c4a908b9d8d2"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.30.1" ]
revision = "3ea501bb38665e52dfde7ff3a172be2b7b51fcea"
