manifest = "79f6dfeec04dff5adbe4a68c91d67375b2080b5351873acc042c5a36d3eff8cd"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.38.0" ]
revision = "f129de05f396dc4d6e5460a69f648766659d4e09"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.38.0" ]
revision = "be230f24a809ac41e584cfd6d843485073012a80"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.38.0" ]
revision = "67680c89217df7d12a280c75e861056e7482aa64"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.38.0" ]
revision = "752752b607d91be4ce2fe0affd8e315f81796b93"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.38.0" ]
revision = "ac36cd1957ed21e9a63225331843132518c57537"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.38.0" ]
revision = "ace4995bb42d6021e9ac34cf80b159afa2aa7345"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.38.0" ]
revision = "052bc304465323f02bea64dca87d3db7c07b457b"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.38.0" ]
revision = "bced377b216e7336710ddbc86d94b09f4f9b0104"
