manifest = "ce0210dc512f1d0abefb6fe6ce827a6fbbc087f4a6a22e4288093c109964d453"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.60.0" ]
revision = "30200cca26f795f074c8cde1612e7ca3e991c6dd"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.60.0" ]
revision = "2cd181f656b7f927f015f31509c278c2f31fb797"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.60.0" ]
revision = "a925c01c552ca5d288538be0f0e16557f35f02ea"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.60.0" ]
revision = "e795f285a98323376ee89e6d825c8113c14decdd"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.60.0" ]
revision = "bcb9f114b1b1d35dded7e0472ca79cd54d70e23a"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.60.0" ]
revision = "9bfe7adc73ff985454f45f7798882393ccbc6f7d"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.60.0" ]
revision = "28f45fecf7dfaaa184eb4fab3db55ec7fca62099"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.60.0" ]
revision = "36602131d924fbc2a2c65c36960b5ea8800f2bb6"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.60.0" ]
revision = "755e1c862e2ad626b448c19c0cd416585c8966e1"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.60.0" ]
revision = "c5cd27a4ffcb3bb08eac7829bb4039f8ed20f95f"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.60.0" ]
revision = "448d84d1d02d60be2e86efd0a99342df23c2f2dd"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.60.0" ]
revision = "a242146f8aa7a5529e75dd9ca56121a608511720"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.60.0" ]
revision = "34a1d2afe76b7443addcc2a23aacbfd1ef950377"
