manifest = "ae0c72a7f739d6fd314ca0130b3189280c9ee45aabdd6050f66574f49371d320"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.33.0" ]
revision = "65a8650af82725f556021c523cb3a87f6b93c268"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.33.0" ]
revision = "40ad58a6eec511d5c9b370e6316df7d27e2ed0ab"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.33.0" ]
revision = "ad24763accac53697cf8657ae40b49be2e0818a8"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.33.0" ]
revision = "80bb3052d207a8a70e7521aa16959979cfcf1e70"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.33.0" ]
revision = "13db417fd9a81f2558365e854caf8d42a9100289"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.33.0" ]
revision = "4acae7173fa1e199cb9bbe0d13bd447e60f5f23d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.33.0" ]
revision = "4f62fa95b94166f6c54732ee7e93c53ea6f25e9a"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.33.0" ]
revision = "43f2eff4cf50a5fde6eaee135260bf7bd7bccb36"
