manifest = "1542ebf22c29588667eb6daae52ae82b807b2d481269b20ac1398e25ccac3317"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.55.0" ]
revision = "892598f066f15a4b8352bbd6b5f2b1a90e12e6fc"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.55.0" ]
revision = "8fe65abe2334e0d84c2cba4c768ec2f2360b33e1"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.55.0" ]
revision = "17efc70a43f3d9379475b9637855b2be09da3bcd"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.55.0" ]
revision = "78443b64adde5fee6ff008e9f3c05d916b394ba4"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.55.0" ]
revision = "f195ab9ac02e1bf52b54bfaebabdeb13d4f019a2"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.55.0" ]
revision = "a41bc5546421204bda9a1572a75474b7197559b2"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.55.0" ]
revision = "e14d6eb7ed4f944d0c0bb723e4732c5ea80d0d1d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.55.0" ]
revision = "e53e7e72e660990dcc5c6c015d724fab0c4516a6"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.55.0" ]
revision = "59b48f8ac824d7985183ffb3c3174c8caebfef20"
