manifest = "662bc27e4d47d79ba6fa57a6130a6a11764f167a6837c388e40ec5f9de95055c"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.69.0" ]
revision = "8c356ca68338cb9dc02e762a7a6fab6972021619"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.69.0" ]
revision = "789954938e5acfbba080099137a47434f1201cca"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.69.0" ]
revision = "d38267954f10bed05fee712ad5aea58aa74816ad"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.69.0" ]
revision = "addd909479c7ff5496cea1039cdb8499c6391c79"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.69.0" ]
revision = "351e7234276fbfc8a8705acfde9b719583aa1634"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.69.0" ]
revision = "9142209a69d7832ff585bc8f81510fb4c830e212"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.69.0" ]
revision = "08a7dee9782c4834df9381598ac7a82aaaae2977"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.69.0" ]
revision = "026118631ec37f5ffdaebf51cfc828abd3cbc44f"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.69.0" ]
revision = "8f9b174b132f4366c11eb474785006fe157319ed"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.69.0" ]
revision = "43a1751b4cfbe193d0a7ae7c79601356e953b1f9"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.69.0" ]
revision = "f86cd306b5ce8c80b6b8c46a8f95716698086c13"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.69.0" ]
revision = "aa5f98074e155e1a2e18c7870e8e2d681951e601"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.69.0" ]
revision = "88a06d226cfbf7cc3559e78a236c04fe104029f2"
