manifest = "9f88fa1546b268cf196188efd20e98c5ac47201811f532b0b1b1aee3405aab39"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.58.0" ]
revision = "ac721f66265e383ac6d7b96996e902332d12783d"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.58.0" ]
revision = "ba2389bfd836700138f7fbd65858501d75276a05"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.58.0" ]
revision = "56d073a8276bae5f86b88b8e967da2e125280c0b"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.58.0" ]
revision = "a36f15fe51460b013e423ed1c83a0fcb719752ba"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.58.0" ]
revision = "2782837f081e7128e2c90d0318deeb6a1a56b782"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.58.0" ]
revision = "64a4ee9e7b86170ee420f688da3eb62185864c10"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.58.0" ]
revision = "4ebe9738d69205dd7361a598afefd262caa3608d"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.58.0" ]
revision = "aa995a705134238256af161bf9627a095fc99cdc"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.58.0" ]
revision = "2b5f853e75e5811875cc344e5a6824cec279e9a7"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.58.0" ]
revision = "f777b1eef66c8145f13ab1077dc6585fbbb7f26a"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.58.0" ]
revision = "b98678fc985c8b428d89a93cc4323def33b4854d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.58.0" ]
revision = "95bd2f3c63ecb05015e31e46b36f84f2d783c972"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.58.0" ]
revision = "464be14cff1e4aa654507df1a6313d366a45d974"
